FROM mcr.microsoft.com/windows:ltsc2019

# Need to disable the progress bar for speeding up the downloads.
# hadolint ignore=SC2086
RUN powershell $Global:ProgressPreference = 'SilentlyContinue'

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Install Visual Studio 2019 Build Tools.
RUN curl -SL --output vs_buildtools.exe https://aka.ms/vs/16/release/vs_buildtools.exe \
    && (start /w vs_buildtools.exe --quiet --wait --norestart --nocache \
    --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools" \
    --add Microsoft.VisualStudio.Workload.VCTools \
    --add Microsoft.VisualStudio.Component.VC.ASAN \
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
    --add Microsoft.VisualStudio.Component.Windows10SDK.19041 \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0) \
    && del /q vs_buildtools.exe

# Install Chocolatey.
# ENV define runtime env var
ENV chocolateyVersion=1.4.0
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

# Install git.
RUN choco install git.install -y
RUN powershell Copy-Item -Recurse -Path 'C:\Program Files\Git' -Destination C:\Git

# Install vcpkg.
# hadolint ignore=DL3003
# -disableMetrics option disables telemetry
# ARG defines build time only env var
# To use the env var in command $Env:VCPKG_RLS_VER, but it only works during build time.
ARG VCPKG_RLS_VER=2026.03.18
RUN powershell -Command "git clone https://github.com/microsoft/vcpkg.git C:\vcpkg; cd C:\vcpkg ; git fetch --all --tags ; git checkout $Env:VCPKG_RLS_VER ; .\bootstrap-vcpkg.bat -disableMetrics"

ADD vcpkg/vcpkg.json .

RUN powershell .\vcpkg\vcpkg.exe install --x-install-root .\vcpkg\installed


ARG JDK_SITE="cdn.azul.com/zulu/bin"
# "8.62.0.19"
ARG JDK_VERSION="11.86.21"
# "8.0.332"
ARG JDK_FULL_VERSION="11.0.30"
ARG JDK_FILENAME="zulu${JDK_VERSION}-ca-jdk${JDK_FULL_VERSION}-win_x64.zip"
# Install Azul Java 8 JDK.
# -UseBasicParsing avoid full html parsing(e.g. Forms, Links, Images, etc.), it only keeps essential .Centent, .Headers, .StatusCode
# $env:TEMP is a built-in PowerShell environment variable, based on your windows version, it can point to
# C:\Windows\Temp
# or sometimes C:\Users\{username}\AppData\Local\Temp
# -Force option will overwrite if file exists already
RUN powershell -Command "Invoke-WebRequest -Uri https://$Env:JDK_SITE/$Env:JDK_FILENAME -OutFile $env:TEMP\$Env:JDK_FILENAME -UseBasicParsing"

RUN powershell -Command "Expand-Archive -Path $env:TEMP\$Env:JDK_FILENAME -DestinationPath C:\Java -Force; Remove-Item -Path $env:TEMP\$Env:JDK_FILENAME -Force"


# Install Apache Maven.
ARG MVN_VER="3.9.11"
ARG MVN_FILE="apache-maven-${MVN_VER}-bin.zip"
RUN powershell -Command "Invoke-WebRequest -URI 'https://archive.apache.org/dist/maven/maven-3/${env:MVN_VER}/binaries/${env:MV_FILE}' -OutFile '$env:TEMP\${env:MVN_FILE}'"
RUN powershell -Command "Expand-Archive -Path '$env:TEMP\${env:MVN_FILE}' -DestinationPath 'C:\Maven'"

# Install CMake 3.19.8.
ARG CMAKE_VER="3.19"
ARG CMAKE_REL="8"
ARG CMAKE_FILE="cmake-${CMAKE_VER}.${CMAKE_REL}-win64-x64.zip"
RUN powershell -Command "Invoke-WebRequest -URI 'https://cmake.org/files/v${env:CMAKE_VER}/${env:CMAKE_FILE}' -OutFile '$env:TEMP\${env:CMAKE_FILE}'"
RUN powershell -Command "Expand-Archive -Path '$env:TEMP\${env:CMAKE_FILE}' -DestinationPath 'C:\CMake'"

# Install zstd 1.5.4.
ARG ZSTD_VER="1.5.4"
ARG ZSTD_FILE="zstd-v${ZSTD_VER}-win64.zip"
RUN powershell -Command "Invoke-WebRequest -Uri 'https://github.com/facebook/zstd/releases/download/v${env:ZSTD_VER}/${env:ZSTD_FILE}' -OutFile '$env:TEMP\${env:ZSTD_FILE}'"
RUN powershell -Command "Expand-Archive -Path '$env:TEMP\${env:ZSTD_FILE}' -DestinationPath 'C:\ZStd'"
RUN setx PATH "%PATH%;C:\ZStd"


# below commands install rsync and its dependencies from https://repo.msys2.org/msys/x86_64/
ARG MSYS_URL="repo.msys2.org/msys/x86_64"

ARG RSYNC_VERSION=3.3.0
ARG RSYNC_RELEASE=1

# rsync dependencies (common working combination for rsync 3.3.0)
ARG LIBOPENSSL_VERSION=3.5.2
ARG LIBOPENSSL_RELEASE=1
ARG LIBOPENSSL_FILE="libopenssl-${LIBOPENSSL_VERSION}-${LIBOPENSSL_RELEASE}-x86_64.pkg.tar.zst"

# Install libopenssl needed for rsync
RUN powershell -Command "Invoke-WebRequest -Uri 'https://${env:MSYS_URL}/${env:LIBOPENSSL_FILE}' -OutFile '$env:TEMP\${env:LIBOPENSSL_FILE}'"
RUN powershell -Command "zstd -d '$env:TEMP\${env:LIBOPENSSL_FILE}' -o '$env:TEMP\libopenssl-${LIBOPENSSL_VERSION}-${LIBOPENSSL_RELEASE}-x86_64.pkg.tar'"
RUN powershell -Command "mkdir 'C:\LibOpenSSL'"
RUN powershell -Command "tar -xvf '$env:TEMP\libopenssl-${LIBOPENSSL_VERSION}-${LIBOPENSSL_RELEASE}-x86_64.pkg.tar' -C 'C:\LibOpenSSL'"

ARG LIBXXHASH_VERSION=0.8.3
ARG LIBXXHASH_RELEASE=1
ARG LIBXXHASH_FILE="libxxhash-${LIBXXHASH_VERSION}-${LIBXXHASH_RELEASE}-x86_64.pkg.tar.zst"
# Install libxxhash needed for rsync
RUN powershell -Command "Invoke-WebRequest -Uri 'https://${env:MSYS_URL}/${env:LIBXXHASH_FILE}' -OutFile '$env:TEMP\${env:LIBXXHASH_FILE}'"
RUN powershell -Command "zstd -d '$env:TEMP\${env:LIBXXHASH_FILE}' -o '$env:TEMP\libxxhash-${LIBXXHASH_VERSION}-${LIBXXHASH_RELEASE}-x86_64.pkg.tar'"
RUN powershell -Command "mkdir 'C:\LibXXHash'"
RUN powershell -Command "tar -xvf '$env:TEMP\libxxhash-${LIBXXHASH_VERSION}-${LIBXXHASH_RELEASE}-x86_64.pkg.tar' -C 'C:\LibXXHash'"

ARG LIBZSTD_VERSION=1.5.6
ARG LIBZSTD_RELEASE=1
ARG LIBZSTD_FILE=1
# Install libzstd needed for rsync
RUN powershell -Command "Invoke-WebRequest -Uri https://$MSYS_URL/libzstd-${LIBZSTD_VERSION}-${LIBZSTD_RELEASE}-x86_64.pkg.tar.zst -OutFile $env:TEMP\libzstd-${LIBZSTD_VERSION}-${LIBZSTD_RELEASE}-x86_64.pkg.tar.zst
RUN powershell -Command "zstd -d $env:TEMP\libzstd-${LIBZSTD_VERSION}-${LIBZSTD_RELEASE}-x86_64.pkg.tar.zst -o $env:TEMP\libzstd-${LIBZSTD_VERSION}-${LIBZSTD_RELEASE}-x86_64.pkg.tar
RUN powershell -Command "mkdir "C:\LibZStd"
RUN powershell -Command "tar -xvf $env:TEMP\libzstd-${LIBZSTD_VERSION}-${LIBZSTD_RELEASE}-x86_64.pkg.tar -C "C:\LibZStd"

# Install rsync
RUN powershell Invoke-WebRequest -Uri https://$MSYS_URL/rsync-${RSYNC_VERSION}-${RSYNC_RELEASE}-x86_64.pkg.tar.zst -OutFile $env:TEMP\rsync-${RSYNC_VERSION}-${RSYNC_RELEASE}-x86_64.pkg.tar.zst
RUN powershell zstd -d $env:TEMP\rsync-${RSYNC_VERSION}-${RSYNC_RELEASE}-x86_64.pkg.tar.zst -o $env:TEMP\rsync-${RSYNC_VERSION}-${RSYNC_RELEASE}-x86_64.pkg.tar
RUN powershell mkdir "C:\RSync"
RUN powershell tar -xvf $env:TEMP\rsync-${RSYNC_VERSION}-${RSYNC_RELEASE}-x86_64.pkg.tar -C "C:\RSync"

# Copy the dependencies of rsync
RUN powershell Copy-Item -Path "C:\LibOpenSSL\usr\bin\*.dll" -Destination "C:\Program` Files\Git\usr\bin"
RUN powershell Copy-Item -Path "C:\LibXXHash\usr\bin\*.dll" -Destination "C:\Program` Files\Git\usr\bin"
RUN powershell Copy-Item -Path "C:\LibZStd\usr\bin\*.dll" -Destination "C:\Program` Files\Git\usr\bin"
RUN powershell Copy-Item -Path "C:\RSync\usr\bin\*" -Destination "C:\Program` Files\Git\usr\bin"

COPY pkg-resolver pkg-resolver

## Install Python 3.11.8.
# The Python installation steps below are derived from -
# https://github.com/docker-library/python/blob/105d6f34e7d70aad6f8c3e249b8208efa591916a/3.11/windows/windowsservercore-ltsc2022/Dockerfile
ENV PYTHONIOENCODING UTF-8
ENV PYTHON_VERSION 3.11.8
ENV PYTHON_PIP_VERSION 24.0
ENV PYTHON_SETUPTOOLS_VERSION 65.5.1
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py
ENV PYTHON_GET_PIP_SHA256 dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9
RUN powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
RUN powershell pkg-resolver\install-python.ps1
RUN powershell pkg-resolver\install-pip.ps1
RUN powershell pip install python-dateutil

## Install the Microsoft Visual C++ 2010 Redistributable to link leveldbjni native library
RUN powershell -Command Invoke-WebRequest -Uri https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe -OutFile vcredist_x64.exe
RUN powershell -Command Start-Process -FilePath .\vcredist_x64.exe -ArgumentList '/quiet', '/norestart' -Wait
RUN powershell -Command Remove-Item vcredist_x64.exe

# Create a user HadoopBuilder with basic privileges and use it for building Hadoop on Windows.
RUN powershell New-LocalUser -Name 'HadoopBuilder' -Description 'User account for building Apache Hadoop' -Password ([securestring]::new()) -AccountNeverExpires -PasswordNeverExpires

# Grant the privilege to create symbolic links to HadoopBuilder.
RUN powershell secedit /export /cfg "C:\secpol.cfg"
RUN powershell "(Get-Content C:\secpol.cfg).Replace('SeCreateSymbolicLinkPrivilege = ', 'SeCreateSymbolicLinkPrivilege = HadoopBuilder,') | Out-File C:\secpol.cfg"
RUN powershell secedit /configure /db "C:\windows\security\local.sdb" /cfg "C:\secpol.cfg"
RUN powershell Remove-Item -Force "C:\secpol.cfg" -Confirm:$false

# Login as HadoopBuilder and set the necessary environment and PATH variables.
USER HadoopBuilder
ENV PROTOBUF_HOME "C:\vcpkg\installed\x64-windows"
ENV JAVA_HOME "C:\Java\zulu8.62.0.19-ca-jdk8.0.332-win_x64"
ENV MAVEN_OPTS '-Xmx2048M -Xss128M'
ENV IS_WINDOWS 1
RUN setx PATH "%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
RUN setx PATH "%PATH%;%JAVA_HOME%\bin"
RUN setx PATH "%PATH%;C:\Maven\apache-maven-3.9.11\bin"
RUN setx PATH "%PATH%;C:\CMake\cmake-3.19.0-win64-x64\bin"
RUN setx PATH "%PATH%;C:\ZStd"
RUN setx PATH "%PATH%;C:\Program Files\Git\usr\bin"
RUN setx PATH "%PATH%;C:\Python"

# The mvnsite module runs a bash script and somewhere down in the invocation, it resorts to call
# /usr/bin/env python3. Thus, we need to create the following symbolic link to satisfy this need.
RUN powershell New-Item -ItemType SymbolicLink -Path "C:\Python\python3" -Target "C:\Python\python.exe"

# We get strange Javadoc errors without this.
RUN setx classpath ""

# Setting Git configurations.
RUN git config --global core.autocrlf true
RUN git config --global core.longpaths true

# Define the entry point for the docker container.
ENTRYPOINT ["C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat", "&&", "cmd.exe"]
